<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2019-01-24
 * Time: 23:11
 */

namespace EasySwoole\EasySwoole\Command;


use EasySwoole\Command\AbstractInterface\CallerInterface;
use EasySwoole\Command\AbstractInterface\ResultInterface;
use EasySwoole\Command\Container;
use EasySwoole\Command\Runner;
use EasySwoole\Component\Singleton;
use EasySwoole\EasySwoole\Command\DefaultCommand\Start;
use EasySwoole\EasySwoole\Config;
use EasySwoole\EasySwoole\Core;


class CommandRunner extends Runner
{
    use Singleton;

    function __construct(Container $container = null)
    {
        parent::__construct($container);
        $this->commandContainer()->set(new Start());
    }

    private $beforeCommand;

    function setBeforeCommand(callable $before)
    {
        $this->beforeCommand = $before;
    }

    function run(CallerInterface $caller): ?ResultInterface
    {
        if(is_callable($this->beforeCommand)){
            call_user_func($this->beforeCommand,$caller);
        }
        Utility::opCacheClear();
        $conf = Config::getInstance();
        //配置环境预选处理
        if(in_array('produce',$caller->getParams())){
            Core::getInstance()->setIsDev(false);
        }else{
            Core::getInstance()->setIsDev(true);
        }
        Core::getInstance()->initialize();
        if (in_array("d", $caller->getParams()) || in_array("daemonize", $caller->getParams())) {
            $conf->setConf("MAIN_SERVER.SETTING.daemonize", true);
        }
        return parent::run($caller); // TODO: Change the autogenerated stub
    }
}