<?php


namespace EasySwoole\EasySwoole\Test;


use EasySwoole\EasySwoole\Config;
use EasySwoole\EasySwoole\Core;
use EasySwoole\EasySwoole\ServerManager;
use EasySwoole\EasySwoole\Swoole\EventRegister;
use PHPUnit\Framework\TestCase;

class ServerTest extends TestCase
{
    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function testServer()
    {
        Core::getInstance()->initialize()->createServer();
        $this->assertInstanceOf(\swoole_http_server::class,ServerManager::getInstance()->getSwooleServer());
        $this->assertEquals(Config::getInstance()->getConf('MAIN_SERVER.SETTING'),ServerManager::getInstance()->getSwooleServer()->setting);
    }

    /**
     * @depends testServer
     * testSubPort
     * @author Tioncico
     * Time: 16:50
     */
    function testSubPort()
    {
        $register = ServerManager::getInstance()->addServer('tcp',9500);
        $this->assertInstanceOf(EventRegister::class,$register);
        $register->add($register::onConnect,'onconnect');
        $this->assertEquals(['onconnect'],$register->get($register::onConnect));
        $sub = ServerManager::getInstance()->getSwooleServer('tcp');
        $this->assertInstanceOf(\swoole_server_port::class,$sub);
    }
}