<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2017/11/9
 * Time: 下午12:22
 */

namespace Core\Component;


class SysConst
{
    const ERROR_HANDLER = 'ERROR_HANDLER';
    const LOGGER_WRITER = 'LOGGER_WRITER';
    const HTTP_EXCEPTION_HANDLER = 'HTTP_EXCEPTION_HANDLER';
    const EXCEPTION_HANDLER = 'EXCEPTION_HANDLER';
    const CONTROLLER_MAX_DEPTH = 'CONTROLLER_MAX_DEPTH';
    const SHARE_MEMORY_FILE = 'SHARE_MEMORY_FILE';
    const TEMP_DIRECTORY = 'TEMP_DIRECTORY';
    const LOG_DIRECTORY = 'LOG_DIRECTORY';
    const VERSION_CONTROL = 'VERSION_CONTROL';
    const SESSION_NAME = 'SESSION_NAME';
    const SESSION_SAVE_PATH = 'SESSION_SAVE_PATH';
    const SESSION_HANDLER = 'SESSION_HANDLER';
    const SESSION_GC_MAX_LIFE_TIME = 'SESSION_GC_MAX_LIFE_TIME';
    const SESSION_GC_PROBABILITY = 'SESSION_GC_PROBABILITY';
    const VERSION = 'VERSION';
    const PIPE_COMMAND_REGISTER = 'PIPE_COMMAND_REGISTER';
}