<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a790a1068656c6c6f776f726c642e70726f746f12046b6a6378222a0a0c" .
            "48656c6c6f52657175657374120c0a046e616d65180120012809120c0a04" .
            "64657363180220012809222b0a0a48656c6c6f5265706c79120f0a076d65" .
            "7373616765180120012809120c0a0464617461180220012809620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

