<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2017/4/11
 * Time: 下午8:47
 */

namespace Core\Component\Spl;


abstract class AbstractSplObject extends SplArray
{
    private $mappingProperty = array();

    /**
     * AbstractSplObject constructor.
     * @param array $array
     */
    function __construct(array $array = array())
    {
        $this->setPropertyMapping();
        $this->initialize($array);
    }

    abstract protected function setPropertyMapping();

    protected function addPropertyMapping($propertyName,$defaultVal = null){
        $this->mappingProperty[$propertyName] = null;
        $this->offsetSet($propertyName,$defaultVal);
        return $this;
    }

    private function initialize(array $data){
        foreach ($this->mappingProperty as $key => $item){
            if(isset($data[$key])){
                $this->offsetSet($key,$data[$key]);
            }
        }
    }

    function __set($name, $value)
    {
       // TODO: Change the autogenerated stub
        if(array_key_exists($name,$this->mappingProperty)){
            parent::__set($name, $value);
        }
    }
}