<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2017/4/11
 * Time: 下午3:01
 */

namespace Core\Component\Spl;


class SplArray extends \ArrayObject
{
    public function __construct(array $array = array())
    {
        parent::__construct($array);
    }

    function __get($name)
    {
        // TODO: Implement __get() method.
        if(isset($this[$name])){
            if(is_array($this[$name])){
                return new SplString($this[$name]);
            }else{
                return $this[$name];
            }
        }else{
            $this->__set($name,new SplArray());
            return $this[$name];
        }
    }

    function __set($name, $value)
    {
        // TODO: Implement __set() method.
        $this[$name] = $value;
    }

    function __toString()
    {
        // TODO: Implement __toString() method.
        return json_encode($this,JSON_UNESCAPED_UNICODE,JSON_UNESCAPED_SLASHES);
    }

    function getArrayCopy()
    {
        $temp = parent::getArrayCopy(); // TODO: Change the autogenerated stub
        foreach ($temp as &$item){
            if($item instanceof SplArray){
                $item = $item->getArrayCopy();
                if(empty($item)){
                    $item = null;
                }
            }
        }
        return $temp;
    }
}