<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2018/8/14
 * Time: 下午6:15
 */

namespace EasySwoole\EasySwoole;


use EasySwoole\Component\Singleton;
use EasySwoole\EasySwoole\Console\TcpService;

class Logger extends \EasySwoole\Trace\Logger
{
    use Singleton;

    function log(string $str, $category = 'default')
    {
        parent::log($str, $category); // TODO: Change the autogenerated stub
        if(Config::getInstance()->getDynamicConf('CONSOLE.PUSH_LOG')){
            TcpService::push("consoleLog ".date("y-m-d H:i:s").": {$str}");
        }
    }

    function console(string $str, $saveLog = 1)
    {
        parent::console($str, $saveLog); // TODO: Change the autogenerated stub
        //当saveLog = true的时候，会自动调用log ,因此不再推送
        if(!$saveLog && Config::getInstance()->getDynamicConf('CONSOLE.PUSH_LOG')){
            TcpService::push("consoleLog ".date("y-m-d H:i:s").": {$str}");
        }
    }
}